openapi: 3.0.2
info:
  version: 1.0.0
  title: Slim API
  contact:
    name: Company AG
    url: 'https://example.com'
    email: apiteam@example.com
  description: |-
    This is a sample RESTful Server based on the OpenAPI 3.0 specification. You can find out more about
    Swagger at [https://swagger.io](https://swagger.io).
  license:
    name: Proprietary License
    url: 'https://en.wikipedia.org/wiki/Proprietary_software'
externalDocs:
  description: External Documentation
  url: 'https://example.com/documentation'
servers:
  - url: 'https://test.example.com/api/v1'
    description: Test
  - url: 'https://staging.example.com/api/v1'
    description: Staging
  - url: 'https://example.com/api/v1'
    description: Production
tags:
  - name: Customer
security:
  - BasicAuth: []
paths:
  '/customers':
    get:
      tags:
        - Customer
      summary: List customers
      description: 'My description.'
      operationId: findCustomers
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customers'
        '400':
          $ref: '#/components/responses/400'
        '403':
          $ref: '#/components/responses/403'
        '422':
          $ref: '#/components/responses/422'
        '500':
          $ref: '#/components/responses/500'
    post:
      tags:
        - Customer
      summary: Create customer
      description: 'My description.'
      operationId: createCustomer
      requestBody:
        description: Created
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Customer'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  customer_id:
                    type: integer
                    format: int32
                    example: 10
        '400':
          $ref: '#/components/responses/400'
        '403':
          $ref: '#/components/responses/403'
        '422':
          $ref: '#/components/responses/422'
        '500':
          $ref: '#/components/responses/500'
  '/customers/{customer_id}':
    get:
      tags:
        - Customer
      summary: Get customer
      description: 'My description.'
      operationId: getCustomerById
      parameters:
        - name: customer_id
          in: path
          description: 'The ID that needs to be fetched.'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
        '400':
          $ref: '#/components/responses/400'
        '403':
          $ref: '#/components/responses/403'
        '422':
          $ref: '#/components/responses/422'
        '500':
          $ref: '#/components/responses/500'
    put:
      tags:
        - Customer
      summary: Update customer
      description: 'My description.'
      operationId: updateCustomer
      parameters:
        - name: customer_id
          in: path
          description: ID that need to be deleted
          required: true
          schema:
            type: string
      requestBody:
        description: Update an existent customer
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Customer'
      responses:
        '200':
          $ref: '#/components/responses/200'
        '400':
          $ref: '#/components/responses/400'
        '403':
          $ref: '#/components/responses/403'
        '422':
          $ref: '#/components/responses/422'
        '500':
          $ref: '#/components/responses/500'
    delete:
      tags:
        - Customer
      summary: Delete customer
      description: 'My description.'
      operationId: deleteCustomer
      parameters:
        - name: customer_id
          in: path
          description: The ID that needs to be deleted
          required: true
          schema:
            type: string
      responses:
        '200':
          $ref: '#/components/responses/200'
        '400':
          $ref: '#/components/responses/400'
        '403':
          $ref: '#/components/responses/403'
        '422':
          $ref: '#/components/responses/422'
        '500':
          $ref: '#/components/responses/500'
components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
  responses:
    '200':
      description: OK.
      content:
        application/json: {}
    '201':
      description: Created.
      content:
        application/json: {}
    '204':
      description: Successfully processed.
      content:
        application/json: {}
    '400':
      description: Bad request.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            error:
              message: Your request does not seem to be valid.
              details:
                - message: 'A more detailed report, if available.'
    '401':
      description: Authorization information is missing or invalid.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            error:
              message: Authorization information is missing or invalid.
    '403':
      description: Forbidden.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            error:
              message: Forbidden. You are not allowed to access this location.
    '404':
      description: Not Found.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            error:
              message: Not Found.
    '405':
      description: Method not allowed.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            error:
              message: Request Method not allowed.
    '406':
      description: Not acceptable.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            error:
              message: The requested format is not supported.
    '415':
      description: Unsupported Media Type.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            error:
              message: The media type is not supported.
    '422':
      description: Unprocessable Entity.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            error:
              message: Input validation failed
              details:
                - field: email
                  message: Invalid email address.
    '500':
      description: Unexpected error.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            error:
              message: Unexpected internal Server Error.
              details:
                - message: 'A more detailed report, if available.'
    '503':
      description: 'Service Unavailable, e.g. Maintenance.'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            error:
              message: Service Unavailable.
              details:
                - message: Barakuda is currently under maintenance.
  schemas:
    Customer:
      type: object
      properties:
        customer_id:
          type: integer
          format: int32
          example: 10
        number:
          type: string
          example: '100001'
        name:
          type: string
          example: 'Acme AG'
        street:
          type: string
          example: '192 Market Square'
        postal_code:
          type: string
          example: '31772'
        city:
          type: string
          example: 'Atlanta'
        country:
          type: string
          example: 'US'
        email:
          type: string
          example: name@example.com
    Customers:
      required:
        - customers
      properties:
        customers:
          type: array
          description: List of customers
          items:
            $ref: '#/components/schemas/Customer'
    Error:
      required:
        - error
      properties:
        error:
          type: object
          required:
            - message
          properties:
            message:
              type: string
              description: The error message
            details:
              type: array
              items:
                $ref: '#/components/schemas/ErrorDetails'
              description: The error details (e.g. validation errors)

    ErrorDetails:
      properties:
        field:
          type: string
          description: The name of the invalid field
        message:
          type: string
          description: The error message
